### ISSUE TITLE
 Failed to access the docker container while running the code.

### ISSUE THREAD

**Issue by saravananpsg** [allenai/deepfigures-open#6]
2018-12-12 17:51:48,308:INFO:scripts.build:Executing: docker build --tag deepfigures-cpu:0.0.1 --file 
Failed to access the docker container while running the code. Kindly let me know how to resolve this error.

**Error Log:** 

/home/saravanan/deepfigures-open/dockerfiles/cpu/Dockerfile .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=dockerfiles%2Fcpu%2FDockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=o7k4ifza9sfm8p1y323f64cp9&shmsize=0&t=deepfigures-cpu%3A0.0.1&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
Traceback (most recent call last):
  File "manage.py", line 70, in <module>
    manage()
  File "/home/saravanan/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/saravanan/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/saravanan/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/saravanan/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/saravanan/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/saravanan/deepfigures-open/scripts/detectfigures.py", line 49, in detectfigures
    build.build.callback()
  File "/home/saravanan/deepfigures-open/scripts/build.py", line 34, in build
    logger)
  File "/home/saravanan/deepfigures-open/scripts/__init__.py", line 54, in execute
    cmd=command)
subprocess.CalledProcessError: Command 'docker build --tag deepfigures-cpu:0.0.1 --file /home/saravanan/deepfigures-open/dockerfiles/cpu/Dockerfile .' returned non-zero exit status 1.

**Comment by SampannaKahu** [comment]
The docker installation on my laptop needs sudo. Try to run your command using sudo.
